### PR TITLE
For #42: Use openjdk8

### PR DESCRIPTION
**Pull request by andreoss**
This is for #42

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by andreoss** [comment]
@rultor can merge?

**Comment by yegor256** [comment]
@rultor merge

**Comment by andreoss** [comment]
@yegor256 The build failure was caused by outdated Lombok being used alongside with jdk 11. 
Please see, https://github.com/jcabi/jcabi/pull/326

If you merge this PR without rultor, it will fix the build in other PRs, since the issue only with jdk 11.

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-matchers#44` is not assigned, can't get performer

**Pull request merged**
