### PR TITLE
modified .gitignore with more files

### PR DESCRIPTION
**Pull request by simonjenga**
modified .gitignore with more files

### CODE REVIEW

**Comment by dmarkov** [comment]
@simonjenga Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@yegor256 Thanks a lot, I just topped your account for **16 mins**, transaction ID `000-586016a7`, total time was 3 hours and 31 mins; extra minutes for review comments (c=1); added +16 to your rating, now it is equal to [+8365](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
