### PR TITLE
Updated copyright section

### PR DESCRIPTION
**Pull request by palyuga**
Issue #16 fixed

### CODE REVIEW

**Comment by dmarkov** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@carlosmiranda it's yours, please review

**Comment by carlosmiranda** [comment]
@rultor Let's merge please.

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@carlosmiranda Thanks for your contribution, **19 mins** was added to your account, payment ID is `50572804`

+19 to your rating, your total score is [+1834](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
