### PR TITLE
#14 added methods containsAnyPattern() and containsAllPatterns()

### PR DESCRIPTION
**Pull request by darkled**

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@yegor256 it's yours, please review

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by darkled** [comment]
@yegor256 Is there any use in trying merge again? It failed due to `NoBrokenLinksTest.findsBrLinksInHtmlWithNamespace` but Travis CI passed the build [correctly](https://travis-ci.org/jcabi/jcabi-matchers/jobs/46127650).

**Comment by yegor256** [comment]
@rultor let's try to merge again

**Comment by dmarkov** [comment]
@yegor256 Much obliged! I've added **20 mins** to your account in payment "000-fd40901c"... +20 added to your rating, current score is: [+5128](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
