### PR TITLE
For #42: Remove obsolete gem options from .rultor.yml

### PR DESCRIPTION
**Pull request by andreoss**
- Remove options
- Use the same versions as for travis

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by andreoss** [comment]
#41 can be merge after this one

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-matchers#43` is not assigned, can't get performer

**Pull request merged**
