### PR TITLE
#21 Estimate Project Size

### PR DESCRIPTION
**Pull request by super132**
For task #21, provide estimate to the project

### CODE REVIEW

**Comment by super132** [comment]
@dmarkov , would you please review this PR? Thanks.

**Comment by dmarkov** [comment]
@super132 Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@longtimeago could you please review this pull request

**Comment by dmarkov** [comment]
> @dmarkov , would you please review this PR? Thanks.

@super132 I will take a look, thanks

**Comment by longtimeago** [comment]
@rultor merge

**Comment by super132** [comment]
@yegor256 would you please review this PR? Thanks.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor deploy

**Comment by dmarkov** [comment]
@longtimeago Thanks a lot, I just topped your account for **16 mins**, transaction ID `58583478`, total time was 118 hours and 40 mins; extra minutes for review comments (c=1); +16 added to your rating, at the moment it is: [+3869](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
